# Generated by Django 5.2.7 on 2025-11-03 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20251103_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='check_cpf_format',
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('cpf__regex', '^\\d{11}$')), name='check_cpf_format'),
        ),
    ]
