# Generated by Django 5.2.7 on 2025-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_cliente_check_cpf_format_vendaitem_backorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento_preferida',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito'), ('boleto', 'Boleto')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito'), ('boleto', 'Boleto')], default='pix', max_length=20),
        ),
    ]
