# Generated by Django 5.2.7 on 2025-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cliente_forma_pagamento_preferida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='confirmacao_token',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='venda',
            name='recebido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('recebido', 'Recebido')], default='novo', max_length=20),
        ),
    ]
