# Generated by Django 5.2.7 on 2025-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_venda_confirmacao_token_venda_recebido_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='confirmacao_token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
