"""Add senha_hash to Cliente

Revision ID: ab2e12f77973
Revises: e368fcf17eaa
Create Date: 2025-09-13 22:35:41.532679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2e12f77973'
down_revision = 'e368fcf17eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
